
---
- name: Install Apache on EC2 instance
  hosts: tag_Name_ec2_instance
  become: yes

  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present

  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Create index.html file
    copy:
      content: "Hello, World!"
      dest: /var/www/html/index.html
      mode: '0644'

