- name: Install Apache Web Server
  hosts: all
  become: true
  tasks:
    - name: Update package cache (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache (Ubuntu)
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache (RHEL)
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and Enable Apache Service
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: started
        enabled: yes
